//! `workz init` — a short setup wizard. It detects the project, asks a few
//! skippable questions, writes a minimal `.workz.toml` (only deviations from the
//! zero-config defaults), and optionally installs the worktree hook for your
//! agent tool. `-y` runs non-interactively with detected defaults.

use anyhow::Result;
use std::io::{self, Write};
use std::path::Path;

use crate::cli::HookHost;
use crate::{git, hook, sync};

/// The decisions the wizard collects. `generate_toml` turns these into config.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct InitChoices {
    /// Copy node_modules instead of symlinking (Vite/Vitest/pnpm escape hatch).
    pub copy_node_modules: bool,
    /// CoW-reflink node_modules (v0.13). Best of both worlds: each worktree
    /// gets its own writeable copy without the multi-minute install cost.
    /// Auto-recommended when the filesystem supports reflink (btrfs/XFS/APFS).
    pub clone_node_modules: bool,
    /// Base port for --isolated (default 3000).
    pub base_port: u16,
    /// Ports per worktree for --isolated (default 10).
    pub port_range_size: u16,
    /// Agent tool to install a worktree hook for, if any.
    pub hook_host: Option<HookHost>,
}

const DEFAULT_BASE_PORT: u16 = 3000;
const DEFAULT_RANGE: u16 = 10;

impl InitChoices {
    fn detected_default() -> Self {
        InitChoices {
            copy_node_modules: false,
            clone_node_modules: false,
            base_port: DEFAULT_BASE_PORT,
            port_range_size: DEFAULT_RANGE,
            hook_host: None,
        }
    }
}

/// Render the choices into a minimal `.workz.toml` (only deviations are emitted).
pub fn generate_toml(choices: &InitChoices) -> String {
    let mut out = String::from(
        "# workz configuration — generated by `workz init`\n# Zero-config defaults apply; only your deviations are listed below.\n",
    );

    if choices.copy_node_modules || choices.clone_node_modules {
        let strategy = if choices.clone_node_modules { "clone" } else { "copy" };
        out.push_str(&format!("\n[sync.overrides]\nnode_modules = \"{strategy}\"\n"));
    }

    if choices.base_port != DEFAULT_BASE_PORT || choices.port_range_size != DEFAULT_RANGE {
        out.push_str("\n[isolation]\n");
        if choices.base_port != DEFAULT_BASE_PORT {
            out.push_str(&format!("base_port = {}\n", choices.base_port));
        }
        if choices.port_range_size != DEFAULT_RANGE {
            out.push_str(&format!("port_range_size = {}\n", choices.port_range_size));
        }
    }

    out
}

/// Run the wizard.
pub fn run(yes: bool) -> Result<()> {
    let root = git::repo_root().unwrap_or_else(|_| std::env::current_dir().unwrap_or_default());
    let summary = sync::detect_summary(&root);
    print_summary(&summary);

    let config_path = root.join(".workz.toml");
    if config_path.exists() && !yes && !prompt_yes_no("\n.workz.toml already exists. Overwrite it?", false)? {
        println!("keeping existing .workz.toml");
        return Ok(());
    }

    let choices = if yes {
        InitChoices::detected_default()
    } else {
        interactive_choices(&root, &summary)?
    };

    let toml = generate_toml(&choices);
    std::fs::write(&config_path, &toml)?;
    println!("\nwrote {}", config_path.display());

    if let Some(host) = choices.hook_host {
        println!();
        // Best-effort install; hook::run prints the outcome (or a merge note).
        if let Err(e) = hook::run(host, true) {
            eprintln!("note: {e}");
        }
    }

    println!("\ndone. Create an isolated worktree with:  workz start <branch> --isolated");
    Ok(())
}

fn print_summary(s: &sync::ProjectSummary) {
    println!("workz init — scanning repository\n");
    if s.languages.is_empty() {
        println!("  language:   (none detected — zero-config defaults still apply)");
    } else {
        println!("  language:   {}", s.languages.join(", "));
    }
    if let Some(cmd) = &s.install_cmd {
        println!("  install:    {cmd}");
    }
    if let Some(fw) = &s.framework {
        println!("  framework:  {fw}");
    }
    if s.has_docker {
        println!("  docker:     docker-compose detected");
    }
    if s.is_monorepo {
        println!("  monorepo:   yes");
    }
}

fn interactive_choices(root: &Path, summary: &sync::ProjectSummary) -> Result<InitChoices> {
    if !prompt_yes_no("\nManage this project with workz?", true)? {
        // Still write a minimal file so defaults are explicit; no extra config.
        return Ok(InitChoices::detected_default());
    }

    let mut choices = InitChoices::detected_default();

    // Node: offer the clone/copy escape hatch. CoW reflink is the v0.13 win
    // — each worktree gets its own real `node_modules` without the install
    // cost, and the agent can't poison the main tree. Auto-detected via
    // probe_reflink_support on the project root.
    if sync::node_project(root) {
        let reflink_ok = sync::probe_reflink_support(root).unwrap_or(false);
        if reflink_ok {
            // Reflink supported: clone is strictly better than copy (no install
            // cost either way; the only cost is the disk until first write).
            let q = if summary.is_monorepo {
                "Use CoW reflink for node_modules? (recommended — each worktree gets an isolated copy that shares storage until you write to it)"
            } else {
                "Use CoW reflink for node_modules? (faster than copy, isolates worktree from agent mutations to deps)"
            };
            choices.clone_node_modules = prompt_yes_no(q, true)?;
            if !choices.clone_node_modules {
                // User declined clone; still offer the regular copy fallback.
                choices.copy_node_modules = prompt_yes_no(
                    "Fall back to a full copy instead?",
                    summary.is_monorepo,
                )?;
            }
        } else {
            // Reflink unsupported: only offer copy.
            let q = if summary.is_monorepo {
                "Copy node_modules instead of symlinking? (recommended for this monorepo — reflink not supported on this filesystem)"
            } else {
                "Copy node_modules instead of symlinking? (needed for some Vite/pnpm setups)"
            };
            choices.copy_node_modules = prompt_yes_no(q, summary.is_monorepo)?;
        }
    }

    // Isolation ports (Enter-through accepts defaults).
    choices.base_port = prompt_u16("Base port for --isolated", DEFAULT_BASE_PORT)?;
    choices.port_range_size = prompt_u16("Ports per worktree", DEFAULT_RANGE)?;

    // Hook install.
    choices.hook_host = prompt_host()?;

    Ok(choices)
}

// ── prompts ──────────────────────────────────────────────────────────────────

fn prompt_yes_no(question: &str, default_yes: bool) -> Result<bool> {
    let hint = if default_yes { "[Y/n]" } else { "[y/N]" };
    print!("{question} {hint} ");
    io::stdout().flush()?;
    let line = read_line()?;
    let ans = line.trim().to_lowercase();
    Ok(match ans.as_str() {
        "" => default_yes,
        "y" | "yes" => true,
        _ => false,
    })
}

fn prompt_u16(question: &str, default: u16) -> Result<u16> {
    print!("{question} [{default}] ");
    io::stdout().flush()?;
    let line = read_line()?;
    let trimmed = line.trim();
    Ok(if trimmed.is_empty() {
        default
    } else {
        trimmed.parse().unwrap_or(default)
    })
}

fn prompt_host() -> Result<Option<HookHost>> {
    print!("Install a worktree hook for which agent tool? (claude/cursor/codex/conductor/worktrunk/none) [none] ");
    io::stdout().flush()?;
    let line = read_line()?;
    Ok(parse_host(line.trim()))
}

/// Map a host name to a HookHost (None for empty/"none"/unknown).
fn parse_host(s: &str) -> Option<HookHost> {
    match s.to_lowercase().as_str() {
        "claude" => Some(HookHost::Claude),
        "cursor" => Some(HookHost::Cursor),
        "codex" => Some(HookHost::Codex),
        "conductor" => Some(HookHost::Conductor),
        "worktrunk" => Some(HookHost::Worktrunk),
        _ => None,
    }
}

fn read_line() -> Result<String> {
    let mut buf = String::new();
    io::stdin().read_line(&mut buf)?;
    Ok(buf)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn minimal_toml_when_no_deviations() {
        let toml = generate_toml(&InitChoices::detected_default());
        // Header only — no override or isolation sections.
        assert!(toml.contains("generated by"));
        assert!(!toml.contains("[sync.overrides]"));
        assert!(!toml.contains("[isolation]"));
        // Must still parse.
        let _: toml::Value = toml::from_str(&toml).unwrap();
    }

    #[test]
    fn emits_copy_override() {
        let c = InitChoices { copy_node_modules: true, ..InitChoices::detected_default() };
        let out = generate_toml(&c);
        assert!(out.contains("[sync.overrides]"));
        assert!(out.contains("node_modules = \"copy\""));
        let v: toml::Value = toml::from_str(&out).unwrap();
        assert_eq!(
            v["sync"]["overrides"]["node_modules"].as_str(),
            Some("copy")
        );
    }

    #[test]
    fn emits_clone_override() {
        let c = InitChoices { clone_node_modules: true, ..InitChoices::detected_default() };
        let out = generate_toml(&c);
        assert!(out.contains("[sync.overrides]"));
        assert!(out.contains("node_modules = \"clone\""));
        let v: toml::Value = toml::from_str(&out).unwrap();
        assert_eq!(
            v["sync"]["overrides"]["node_modules"].as_str(),
            Some("clone")
        );
    }

    #[test]
    fn clone_wins_over_copy_in_toml() {
        // Defensive: if both somehow get set, clone takes precedence (the
        // newer, more capable strategy).
        let c = InitChoices {
            copy_node_modules: true,
            clone_node_modules: true,
            ..InitChoices::detected_default()
        };
        let out = generate_toml(&c);
        assert!(out.contains("node_modules = \"clone\""));
        assert!(!out.contains("node_modules = \"copy\""));
    }

    #[test]
    fn emits_isolation_only_when_nondefault() {
        let c = InitChoices { base_port: 4000, port_range_size: 20, ..InitChoices::detected_default() };
        let out = generate_toml(&c);
        assert!(out.contains("[isolation]"));
        assert!(out.contains("base_port = 4000"));
        assert!(out.contains("port_range_size = 20"));
    }

    #[test]
    fn parse_host_maps_names() {
        assert!(matches!(parse_host("cursor"), Some(HookHost::Cursor)));
        assert!(matches!(parse_host("CLAUDE"), Some(HookHost::Claude)));
        assert!(parse_host("none").is_none());
        assert!(parse_host("").is_none());
        assert!(parse_host("nonsense").is_none());
    }
}
